In [42]:
import numpy as np
data = (np.arange(10)+10).tolist()
for (index, value) in enumerate(data):
    print(index, value)

0 10
1 11
2 12
3 13
4 14
5 15
6 16
7 17
8 18
9 19


In [43]:
#generator
generator_ex = (x*x for x in range(10))
for i in generator_ex:
    print(i)

0
1
4
9
16
25
36
49
64
81


In [124]:
def fib(max):
    n,a,b =0,0,1
    while n < max:
        yield b
        a,b =b,a+b
        n = n+1
    return 'done'


In [126]:
a = fib(10)
list(a)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

In [127]:
fib(10)

<generator object fib at 0x00000230445D2510>

In [51]:
a = fib(10)
a.__next__()

1

In [52]:
for i in fib(4):
    print(i)

1
1
2
3


In [ ]:
迭代器包含有next方法的实现，在正确的范围内返回期待的数据以及超出范围后能够抛出StopIteration的错误停止迭代。

In [53]:
next(a)

1

In [54]:
a.send(5)

2

In [55]:
next(a)

3

In [108]:
def fib(max):
    n,a,b =0,0,1
    while n < max:
        b = yield
        a,b =b,a+b
        yield b, n, a
        n = n+1
    return 'done'

In [114]:
a = fib(10)

In [121]:
a.__next__()

In [122]:
print(a.send(20))

(40, 3, 20)


In [ ]:
也是用def定义的，利用关键字yield一次性返回一个结果，阻塞，重新开始

In [123]:
list(x ** 3 for x in range(5))

[0, 1, 8, 27, 64]

In [ ]:
isinstance(100, Iterable)
isinstance((x for x in range(10)), Iterable)

In [ ]:
一个实现了iter方法的对象是可迭代的，一个实现next方法并且是可迭代的对象是迭代器。

可以被next()函数调用并不断返回下一个值的对象称为迭代器：Iterator。

所以一个实现了iter方法和next方法的对象就是迭代器。

可以使用isinstance()判断一个对象是否是Iterator对象

In [ ]:
生成器都是Iterator对象，但list、dict、str虽然是Iterable（可迭代对象），却不是Iterator（迭代器）。

把list、dict、str等Iterable变成Iterator可以使用iter()函数：

In [ ]:
>>> isinstance(iter([]), Iterator)
True
>>> isinstance(iter('abc'), Iterator)
True

In [ ]:
你可能会问，为什么list、dict、str等数据类型不是Iterator？

这是因为Python的Iterator对象表示的是一个数据流，Iterator对象可以被next()函数调用并不断返回下一个数据，直到没有数据时抛出StopIteration错误。可以把这个数据流看做是一个有序序列，但我们却不能提前知道序列的长度，只能不断通过next()函数实现按需计算下一个数据，所以Iterator的计算是惰性的，只有在需要返回下一个数据时它才会计算。

Iterator甚至可以表示一个无限大的数据流，例如全体自然数。而使用list是永远不可能存储全体自然数的。

In [ ]:
（4）带有yield的函数不再是一个普通的函数，而是一个生成器generator，可用于迭代

　　（5）yield是一个类似return 的关键字，迭代一次遇到yield的时候就返回yield后面或者右面的值。而且下一次迭代的时候，从上一次迭代遇到的yield后面的代码开始执行

　　（6）yield就是return返回的一个值，并且记住这个返回的位置。下一次迭代就从这个位置开始。

　　（7）带有yield的函数不仅仅是只用于for循环，而且可用于某个函数的参数，只要这个函数的参数也允许迭代参数。

　　（8）send()和next()的区别就在于send可传递参数给yield表达式，这时候传递的参数就会作为yield表达式的值，而yield的参数是返回给调用者的值，也就是说send可以强行修改上一个yield表达式值。

　　（9）send()和next()都有返回值，他们的返回值是当前迭代遇到的yield的时候，yield后面表达式的值，其实就是当前迭代yield后面的参数。

　　（10）第一次调用时候必须先next（）或send（）,否则会报错，send后之所以为None是因为这时候没有上一个yield，所以也可以认为next（）等同于send(None)

anoymous function, lamda function

In [ ]:
lambda x, y: x+y

ternary operator
1 if condition else 2

data.apply(lambda x: 85 if x> 70 else x)

map function,   r = map(function, iterable)
return list(r)

In [10]:
m = map(lambda x, y : x*x+y,[1,2,3,4,5],[2]*5)

In [11]:
m

In [12]:
list(m)

[3, 6, 11, 18, 27]

filter

In [29]:
m = filter(lambda x: len(x.strip())>1, [' ','     ?','ai'])

In [30]:
list(m)

['ai']

reduce, using the last operation result, output one value and 
reduce(function, iterable, init_value)

In [32]:
from functools import reduce

In [33]:
f = lambda x, y : x + y
r = reduce(f, [1,2,3,4,5],10)
print(r)

25


list comprehension
m = [i*i for i in list if i > 3]

dictionary comprehension
d = {"z":20,
     "s":10,
     "m",5
    }
    
d1 = {value: key for key,value in d.items()}

closure a function which returns another function


闭包可以保存当前的运行环境


In [ ]:
def make_filter(flag):
    def the_filter(file_name):
        file = open(file_name)
        lines = file.readlinese()
        file.close()
        file_doc = [i for i in lines if i == keep]
        return file_doc
    return the_filter

装饰器本质上是一个 Python 函数或类，它可以让其他函数或类在不需要做任何代码修改的前提下增加额外功能，装饰器的返回值也是一个函数/类对象。它经常用于有切面需求的场景，比如：插入日志、性能测试、事务处理、缓存、权限校验等场景，装饰器是解决这类问题的绝佳设计。有了装饰器，我们就可以抽离出大量与函数功能本身无关的雷同代码到装饰器中并继续重用。概括的讲，装饰器的作用就是为已经存在的对象添加额外的功能。


有了 @ ，我们就可以省去foo = use_logging(foo)这一句了，直接调用 foo() 即可得到想要的结果。你们看到了没有，foo() 函数不需要做任何修改，只需在定义的地方加上装饰器，调用的时候还是和以前一样，如果我们有其他的类似函数，我们可以继续调用装饰器来修饰函数，而不用重复修改函数或者增加新的封装。这样，我们就提高了程序的可重复利用性，并增加了程序的可读性。

装饰器不仅可以是函数，还可以是类，相比函数装饰器，类装饰器具有灵活度大、高内聚、封装性等优点。使用类装饰器主要依靠类的__call__方法，当使用 @ 形式将装饰器附加到函数上时，就会调用此方法。

In [35]:
class Foo(object):
    def __init__(self, func):
        self._func = func

    def __call__(self):
        print ('class decorator runing')
        self._func()
        print ('class decorator ending')

@Foo
def bar():
    print ('bar')

bar()

class decorator runing
bar
class decorator ending


函数 f 被with_logging取代了，当然它的docstring，__name__就是变成了with_logging函数的信息了。好在我们有functools.wraps，wraps本身也是一个装饰器，它能把原函数的元信息拷贝到装饰器里面的 func 函数中，这使得装饰器里面的 func 函数也有和原函数 foo 一样的元信息了。

In [38]:
from functools import wraps
def logged(func):
    @wraps(func)
    def with_logging(*args, **kwargs):
        print(func.__name__)     # 输出 'f'
        print(func.__doc__)       # 输出 'does some math'
        return func(*args, **kwargs)
    return with_logging

@logged
def f(x):
   """does some math"""
   return x + x * x

In [34]:
def use_logging(level):
    def decorator(func):
        def wrapper(*args, **kwargs):
            if level == "warn":
                logging.warn("%s is running" % func.__name__)
            elif level == "info":
                logging.info("%s is running" % func.__name__)
            return func(*args)
        return wrapper

    return decorator

@use_logging(level="warn")
def foo(name='foo'):
    print("i am %s" % name)

In [ ]:
装饰器顺序
一个函数还可以同时定义多个装饰器，比如：

In [ ]:
@a
@b
@c
def f ():
    pass

In [ ]:
它的执行顺序是从里到外，最先调用最里层的装饰器，最后调用最外层的装饰器，它等效于

f = a(b(c(f)))

no parameter decoration

In [5]:
import time
def runtime(func):
    def get_time():
        print(time.time())
        func()
    return get_time

@runtime
def student():
    print("hello")

student()

1607056533.8908656
hello


parameter decoration without length restriction

In [12]:
import time
def runtime(func):
    def get_time(*args):
        print(time.time())
        func(*args)
    return get_time

@runtime
def student(a,b):
    print("hello")

@runtime
def student1(a):
    print("hello")
    
student(1,2)
student1(3)

1607056803.578743
hello
1607056803.578743
hello


In [14]:
import time
def runtime(func):
    def get_time(*args, **kwargs):
        print(time.time())
        func(*args, **kwargs)
    return get_time

@runtime
def student(*args, **kwargs):
    print("hello")

@runtime
def student1(*args, **kwargs):
    print("hello")
    
student(1,2)
student1(3,i=7)

1607056967.6297421
hello
1607056967.6297421
hello


condition array

In [19]:
import numpy as np
x_arr = np.array([1.1,1.2,1.3])
y_arr = np.array([0,3,4])
condition = np.array([True , False, False])

res1 = [x if c else y for x,y,c in zip(x_arr, y_arr, condition)]


In [20]:
res1

[1.1, 3, 4]

In [21]:
np.where(condition,x_arr,y_arr)

array([1.1, 3. , 4. ])

In [22]:
np.where(x_arr>1.2, 3,10)

array([10, 10,  3])

numpy can read 01 data or text data in the hard desk

np.save/np.load at .npy file
np.savez/np.load at .npz file compression file

In [23]:
arr = np.arange(3)
np.save('np3',arr)


In [24]:
b = np.load('np3.npy')

In [25]:
b

array([0, 1, 2])

In [27]:
np.savez("np3z",arr)


In [28]:
b = np.load("np3z.npz")

In [29]:
b

In [32]:
np.savez("np3z",a=arr)
b = np.load("np3z.npz")['a']

In [33]:
b

array([0, 1, 2])

In [34]:
np.savetxt("nptext", arr, delimiter=',')

In [35]:
np.loadtxt("nptext", delimiter=',')

array([0., 1., 2.])

# PANDAS

isnull, notnull, 

In [2]:
import numpy as np
import pandas as pd
dates = pd.date_range('20201214', periods=6)
print(dates)

DatetimeIndex(['2020-12-14', '2020-12-15', '2020-12-16', '2020-12-17',
               '2020-12-18', '2020-12-19'],
              dtype='datetime64[ns]', freq='D')


In [3]:
df = pd.DataFrame(np.random.rand(6,4), index = dates, columns=list('asdd'))

In [4]:
df

a         s         d         d
2020-12-14  0.679213  0.429055  0.288263  0.954211
2020-12-15  0.240382  0.409309  0.275896  0.870190
2020-12-16  0.734514  0.132183  0.994737  0.330355
2020-12-17  0.645876  0.963985  0.539226  0.634446
2020-12-18  0.562420  0.389401  0.095905  0.317981
2020-12-19  0.142140  0.610714  0.407406  0.304924

In [5]:
# index search
# df.loc['20201214':'20201216',['a','s']]
# df.at[dates[0],'a']


In [7]:
df.iloc[0,2]

0.2882630438814062

df.reindex([], fill_value=0) fill_value for nan 



In [12]:
obj = pd.Series([4.5,0.1,0.5],index=[0,2,4])
obj = obj.reindex(range(6), method='ffill')

In [13]:
obj

0    4.5
1    4.5
2    0.1
3    0.1
4    0.5
5    0.5
dtype: float64

In [ ]:
# ffill forward fill
# bfill backward fill


# math operation

In [14]:
df1 = pd.DataFrame(np.arange(6).reshape(2,3), index = range(2), columns=list('abc'))

In [15]:
df1

a  b  c
0  0  1  2
1  3  4  5

In [16]:
df2 = pd.DataFrame(np.arange(12).reshape(4,3), index = range(4), columns=list('ghc'))

In [17]:
df2

g   h   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [18]:
df1 + df2

a   b     c   g   h
0 NaN NaN   4.0 NaN NaN
1 NaN NaN  10.0 NaN NaN
2 NaN NaN   NaN NaN NaN
3 NaN NaN   NaN NaN NaN

In [19]:
df1.add(df2, fill_value = 100)

a      b      c      g      h
0  100.0  101.0    4.0  100.0  101.0
1  103.0  104.0   10.0  103.0  104.0
2    NaN    NaN  108.0  106.0  107.0
3    NaN    NaN  111.0  109.0  110.0

In [20]:
frame = pd.DataFrame(np.arange(6).reshape(2,3), index = range(2), columns=list('abc'))
series = frame.loc[0]

In [21]:
frame

a  b  c
0  0  1  2
1  3  4  5

In [22]:
series

a    0
b    1
c    2
Name: 0, dtype: int32

In [25]:
frame2 = pd.DataFrame(frame-series, columns=list('bcd'))

In [26]:
frame2


b  c   d
0  0  0 NaN
1  3  3 NaN

In [27]:
frame + frame2

a  b  c   d
0 NaN  1  2 NaN
1 NaN  7  8 NaN

In [ ]:
# df.sort_index()
# df.sort_values()
# df.sort_index(axis = 1)
# df.sort_values(by=column)

# multiple index 

In [37]:
df = pd.Series(np.random.rand(5), index = [['a']*2 + ['b']*3, list(range(5))])

In [38]:
df

a  0    0.643957
   1    0.408005
b  2    0.670157
   3    0.958247
   4    0.935338
dtype: float64

In [39]:
df['a']

0    0.643957
1    0.408005
dtype: float64

In [40]:
df[0]

0.6439566084572265

In [41]:
df[:][1]

0.40800522212177237

In [42]:
# unstack() from series to dataframe
df.unstack()

0         1         2         3         4
a  0.643957  0.408005       NaN       NaN       NaN
b       NaN       NaN  0.670157  0.958247  0.935338

In [43]:
df.unstack().stack()

a  0    0.643957
   1    0.408005
b  2    0.670157
   3    0.958247
   4    0.935338
dtype: float64

In [47]:
df = pd.DataFrame(np.random.rand(8).reshape(4,2), index = [list('aabb'),[0,1,0,3]], columns=[list('ry'),[0,1]]
                                                               )

In [48]:
df

r         y
            0         1
a 0  0.787685  0.825619
  1  0.341602  0.579413
b 0  0.883403  0.392252
  3  0.126957  0.854970

In [51]:
df.stack()

r         y
a 0 0  0.787685       NaN
    1       NaN  0.825619
  1 0  0.341602       NaN
    1       NaN  0.579413
b 0 0  0.883403       NaN
    1       NaN  0.392252
  3 0  0.126957       NaN
    1       NaN  0.854970

In [52]:
df.unstack()

r                             y                   
          0                             1                   
          0         1         3         0         1        3
a  0.787685  0.341602       NaN  0.825619  0.579413      NaN
b  0.883403       NaN  0.126957  0.392252       NaN  0.85497

In [60]:
df.index.names=(['key1','key2'])

In [61]:
df

r         y
                  0         1
key1 key2                    
a    0     0.787685  0.825619
     1     0.341602  0.579413
b    0     0.883403  0.392252
     3     0.126957  0.854970

In [63]:
df.columns.names=['c1','c2']

In [64]:
df

c1                r         y
c2                0         1
key1 key2                    
a    0     0.787685  0.825619
     1     0.341602  0.579413
b    0     0.883403  0.392252
     3     0.126957  0.854970

In [78]:
df.loc['a'].loc[0] # index by layer

c1  c2
r   0     0.787685
y   1     0.825619
Name: 0, dtype: float64

In [79]:
df['r']

c2                0
key1 key2          
a    0     0.787685
     1     0.341602
b    0     0.883403
     3     0.126957

In [82]:
df['r'][0]

key1  key2
a     0       0.787685
      1       0.341602
b     0       0.883403
      3       0.126957
Name: 0, dtype: float64

In [83]:
df

c1                r         y
c2                0         1
key1 key2                    
a    0     0.787685  0.825619
     1     0.341602  0.579413
b    0     0.883403  0.392252
     3     0.126957  0.854970

In [84]:
df.sum()

c1  c2
r   0     2.139646
y   1     2.652254
dtype: float64

In [85]:
df.sum(level='key2')

c1           r         y
c2           0         1
key2                    
0     1.671087  1.217871
1     0.341602  0.579413
3     0.126957  0.854970

In [86]:
df.sum(axis=1)

key1  key2
a     0       1.613303
      1       0.921015
b     0       1.275655
      3       0.981927
dtype: float64

pd.read_csv('', header=None, split='\t', index_col=['c','d'])
NA in text will be NaN
pd.isnull(data)
pd.read_csv('data.csv', nrows=5)
data.to_csv('data.csv',sep='|')

excel = pd.read_excel('data.xlsx', sheet_name='sheet2')
pl = excel.plot(kind='scatter',x='age',y='place').get_figure()

pl.savefig(1.pdf)

matplotlib.pyplot as plt
fig = plt.figure()
ax1 = fig.add_subplot(2,2,1)